# rustfmt.toml - Customize formatting for rustfmt

# Allow very long lines
max_width = 500

# Keep function arguments, return types, etc. on the same line if possible
fn_args_layout = "Compressed"

# Don't force newline after struct or enum definition if it fits in the line
struct_lit_style = "Compressed"
struct_field_align_threshold = 500

# Keep where clauses on the same line if they fit
where_single_line = true

# Do not wrap chains of method calls unless absolutely necessary
chain_width = 500

# Don't break up single-line expressions into multiline
wrap_comments = false

# Keep attributes on the same line when possible
merge_derives = true
