[package]
name = "cyntax_ast_lower"
version = "0.1.0"
edition = "2024"

[dependencies]
cyntax_common = {path = "../cyntax_common"}
cyntax_errors = {path = "../cyntax_errors"}
cyntax_parser = {path = "../cyntax_parser"}
cyntax_hir = {path = "../cyntax_hir"}
bumpalo = "3.17.0"
typed-arena = "2.0.2"
