[package]
name = "cyntax_hir"
version = "0.1.0"
edition = "2024"

[dependencies]
cyntax_common = {path = "../cyntax_common"}
cyntax_errors = {path = "../cyntax_errors"}
cyntax_parser = {path = "../cyntax_parser"}